[package]
name = "time-scheduler-server"
description = "A server for the time-scheduler app"
version = "1.0.0"
edition = "2021"
license = "MIT"
authors = ["Dr-42"]
repository = "https://github.com/Dr-42/time-scheduler-server"

[dependencies]
axum = "0.7.9"
sha256 = "1.5.0"
rpassword = "7.3.1"
tokio = { version = "1.41.1", features = ["full"] }
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
